# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/apollo-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/apollo-miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/product/etc/device_features/apollo.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/device_features/apollo.xml \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/etc/permissions/vendor.xiaomi.hardware.campostproc-V1.0-java-permission.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/vendor.xiaomi.hardware.campostproc-V1.0-java-permission.xml \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib/libarcsoft_single_chart_calibration.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libarcsoft_single_chart_calibration.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib/vendor.xiaomi.hardware.campostproc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.xiaomi.hardware.campostproc@1.0.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libarcsoft_single_chart_calibration.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libarcsoft_single_chart_calibration.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libgallery_arcsoft_dualcam_refocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgallery_arcsoft_dualcam_refocus.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libgallery_arcsoft_portrait_lighting.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgallery_arcsoft_portrait_lighting.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libgallery_arcsoft_portrait_lighting_c.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgallery_arcsoft_portrait_lighting_c.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libgallery_block_sdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgallery_block_sdk.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/libgallery_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgallery_mpbase.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/lib64/vendor.xiaomi.hardware.campostproc@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.xiaomi.hardware.campostproc@1.0.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libAIPOSE.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libAIPOSE.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libCameraEffectJNI.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libCameraEffectJNI.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libDocumentProcess.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libDocumentProcess.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libOCR.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libOCR.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libYuvWatermark.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libYuvWatermark.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libc++.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libc++.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libc++_shared.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_arcsoft_handgesture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_arcsoft_handgesture.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_handgesture_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_handgesture_mpbase.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_mi_handgesture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_mi_handgesture.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_requestutil_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_requestutil_jni.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_video_mein_algo_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_video_mein_algo_jni.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_yuv_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libcamera_yuv_jni.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libdmabufheap.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libdmabufheap.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libhandengine.arcsoft.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libhandengine.arcsoft.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libijkffmpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libijkffmpeg.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libijkplayer.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libijkplayer.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libijksdl.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libijksdl.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libion.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libion.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libmialgo_saliency.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libmialgo_saliency.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libmialgo_saliency_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libmialgo_saliency_jni.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libmiocr_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libmiocr_wrapper.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libmiuiblursdk.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libmiuiblursdk.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libmulti-wakeup-engine.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libmulti-wakeup-engine.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libtailor.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libtailor.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libvideo_extra_color_converter.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libvideo_extra_color_converter.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libvideo_extra_interpolator.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libvideo_extra_interpolator.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/system/priv-app/MiuiCamera/lib/arm64-v8a/libyuv.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64-v8a/libyuv.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/bin/hw/vendor.xiaomi.hardware.campostproc@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.xiaomi.hardware.campostproc@1.0-service \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.campostproc@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.campostproc@1.0-service.rc \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib/hw/vendor.xiaomi.hardware.campostproc@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.xiaomi.hardware.campostproc@1.0-impl.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib/libcom.xiaomi.metadatautils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcom.xiaomi.metadatautils.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib/libcom.xiaomi.pluginutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcom.xiaomi.pluginutils.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib/libswregistrationalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libswregistrationalgo.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib/vendor.xiaomi.hardware.campostproc@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.xiaomi.hardware.campostproc@1.0.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.qcom.plugin.gpu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.qcom.plugin.gpu.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.qcom.plugin.jpegencode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.qcom.plugin.jpegencode.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.bodyslim.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.bodyslim.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.capbokeh.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.capbokeh.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.dc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.dc.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.depurple.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.depurple.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.hdr.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.ldc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.ldc.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.memcpy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.memcpy.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.miaideblur.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.miaideblur.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.miaiie.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.miaiie.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.mibokeh.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.mibokeh.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.miflaw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.miflaw.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.mifragment.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.mifragment.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.misegment.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.misegment.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.skinbeautifier.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.skinbeautifier.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.sr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.sr.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.supernight.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.supernight.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/com.xiaomi.plugin.superportrait.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.xiaomi.plugin.superportrait.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/hw/vendor.xiaomi.hardware.campostproc@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.xiaomi.hardware.campostproc@1.0-impl.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/lib_sr_models.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_sr_models.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libalAILDC.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalAILDC.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libalCFR.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalCFR.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libalLDC.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalLDC.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libalhLDC.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalhLDC.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libarcsat.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsat.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libbeauty_face_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbeauty_face_interface.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libcom.xiaomi.metadatautils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcom.xiaomi.metadatautils.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libcom.xiaomi.pluginutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcom.xiaomi.pluginutils.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libflaw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libflaw.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libmiai_deblur.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiai_deblur.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libmiai_portraitsupernight.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiai_portraitsupernight.so \
    vendor/xiaomi/apollo-miuicamera/common/proprietary/vendor/lib64/libsdk_sr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdk_sr.so

PRODUCT_PACKAGES += \
    MiuiCamera \
    vendor.xiaomi.hardware.campostproc-V1.0-java
